<?php
namespace gamboamartin\documento\controllers;


use gamboamartin\errores\errores;
use stdClass;

class controlador_adm_grupo extends \gamboamartin\acl\controllers\controlador_adm_grupo {
    public function modifica(bool $header, bool $ws = false, array $keys_selects = array(), array $not_actions = array()): array|stdClass
    {
        $not_actions[] = 'usuarios';
        $not_actions[] = 'asigna_permiso';
        $r_modifica =  parent::modifica(header: false,ws:  $ws,keys_selects:  $keys_selects, not_actions: $not_actions); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al maquetar template',data:  $r_modifica,header: $header,ws: $ws);
        }



        return $r_modifica;
    }
}